version: '3.1'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: <<local-machine-ip>>:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<<local-machine-ip>>:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1